name       : gjitenkai
version    : 0.1.4
release    : 3
source     :
    - https://github.com/odrevet/gjiten-kai/archive/refs/tags/v0.1.4.tar.gz : f84c2f2e930d71cf1817fa0a60d60e7649ed2ba5ee0ede16f9452005acc53a5c
license    : GPL-3.0
component  : office
summary    : A new implementation of Gjiten, a Gnome japanese dictionary
description: |
    A new implementation of Gjiten, a Gnome japanese dictionary
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
