name       : gjitenkai
version    : 0.1
release    : 1
source     :
    - https://github.com/odrevet/gjitenkai/archive/0.1.tar.gz : f7368bcad35ec1300cfa628bee563e348e93db9e54b807f7bd5d2f4941ed8abd
license    : GPL-3.0
component  : office
summary    : A new implementation of Gjiten, a Gnome japanese dictionary
description: |
    A new implementation of Gjiten, a Gnome japanese dictionary
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
